# Generated by Django 6.0.4 on 2026-04-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='idempotency_key',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
    ]
