# Generated by Django 6.0.4 on 2026-04-14 10:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_job_idempotency_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobDLQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('error_trace', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dlq_entries', to='jobs.job')),
            ],
        ),
    ]
