# Generated by Django 6.0.4 on 2026-04-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobdlq'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='timeout_seconds',
            field=models.IntegerField(blank=True, default=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('DEAD', 'Dead')], default='PENDING', max_length=20),
        ),
    ]
