# Generated by Django 6.0.4 on 2026-05-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_queuemetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='priority',
            field=models.IntegerField(default=2),
        ),
    ]
